chmod +x mjpgdevvideo1.sh
chmod +x mjpgdevvideo2.sh
chmod +x mjpgdevvideo3.sh
chmod +x mjpgdevvideo4.sh
chmod +x mjpgdevvideo5.sh
chmod +x mjpgdevvideo6.sh
chmod +x mjpgdevvideo7.sh
chmod +x mjpgdevvideo8.sh
chmod +x mjpgdevvideo9.sh
chmod +x mjpgdevvideo10.sh
chmod +x mjpgdevvideo11.sh
chmod +x mjpgdevvideo12.sh
chmod +x mjpgdevvideo13.sh
chmod +x mjpgdevvideo14.sh
chmod +x mjpgdevvideo15.sh
chmod +x mjpgdevvideo16.sh
chmod +x mjpgdevvideo17.sh
chmod +x mjpgdevvideo18.sh
chmod +x mjpgdevvideo19.sh
chmod +x mjpgdevvideo20.sh
chmod +x mjpgdevvideo21.sh
chmod +x mjpgdevvideo22.sh
chmod +x mjpgdevvideo23.sh
chmod +x mjpgdevvideo24.sh
chmod +x mjpgdevvideo25.sh
chmod +x mjpgdevvideo26.sh
